version: '3.8'

services:
  add_subtitles:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: add_subtitles_container
    volumes:
      - ${HOST_VIDEOS_PATH}:/app/videos
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python -u src/launch.py
